import { Controller, Post, Body } from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBody,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';

@ApiTags('Authentication')
@Controller('auth')
export class AuthController {
  @Post('login')
  @ApiOperation({
    summary: 'Wallet-based authentication',
    description:
      'Authenticates a user using a wallet address and a signed message. ' +
      'Returns a JWT access token on successful verification.',
  })
  @ApiBody({
    description: 'Wallet authentication payload',
    schema: {
      type: 'object',
      required: ['walletAddress', 'signature'],
      properties: {
        walletAddress: {
          type: 'string',
          example: 'GBRPYHIL2C2K5H4N6QKX7ZP4ZQJYJ5JH2FQYQ6FZQKX7ZP4ZQJY',
          description: 'User Stellar wallet address',
        },
        signature: {
          type: 'string',
          example: 'MEQCIGy3...signed_payload...9Rw=',
          description: 'Signature generated by signing a server-provided nonce',
        },
      },
    },
  })
  @ApiResponse({
    status: 200,
    description: 'Authentication successful',
    schema: {
      type: 'object',
      properties: {
        accessToken: {
          type: 'string',
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        },
      },
    },
  })
  @ApiUnauthorizedResponse({
    description: 'Invalid wallet signature or unauthorized wallet',
  })
  login(
    @Body()
    body: {
      walletAddress: string;
      signature: string;
    },
  ) {
    // Auth logic intentionally handled elsewhere
    return {
      accessToken: 'jwt-token-placeholder',
    };
  }
}
