# ENDPOINT TO FETCH ALL USERS 
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJNRU5UT1IiLCJpYXQiOjE3NDc3MzEyNzUsImV4cCI6MTc0NzgxNzY3NX0.LoqeMULFW9lG4rGykzt0m4nrTmzSNrYV113O66HroMU