# ENDPOINT TO REGISTER A USER 
POST http://localhost:3000/auth/signup
Content-Type: application/json
{
  "email": "ahmad@leadway.com",
  "password": "Leadway@01",
  "role": "MENTOR"
}

# ENDPOINT TO LOG-IN A USER
POST http://localhost:3000/auth/signin
Content-Type: application/json 
{
  "email": "ahmad@leadway.com",
  "password": "Leadway@001"
}

# ENDPOINT TO CHANGE A USERS PASSWORD 
POST http://localhost:3000/auth/change-password
Authorization: Bearer 
Content-Type: application/json
{
  "currentPassword": "Leadway@01",
  "newPassword": "Leadway@001",
  "confirmNewPassword": "Leadway@001"
}

